# From https://github.com/kubernetes/charts/blob/master/.travis.yml
language: go

go: 
  - 1.6

install:
  - wget http://storage.googleapis.com/kubernetes-helm/helm-v2.0.0-beta.2-linux-amd64.tar.gz
  - tar zxvf helm-v2.0.0-beta.2-linux-amd64.tar.gz

script:
  - linux-amd64/helm lint * --strict
