apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: grafana
  name: prometheus-grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:3.1.1-1470047149
        env:
        - name: GF_SERVER_ROOT_URL
          value: {{.Values.GrafanaURL}}
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
      volumes:
      - name: grafana-storage
        emptyDir: {}
      nodeSelector:
        prometheus: "true"
