apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: core
  annotations:
    prometheus.io/scape: 'true'
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus
    component: core
