apiVersion: v1
kind: ReplicationController
metadata:
  name: {{.Release.Name}}-redis-sa
  labels:
    heritage: helm
    chartName: {{.Chart.Name}}
    chartVersion: {{.Chart.Version | quote}}
    provider: {{.Release.Name}}-redis-sa
  annotations:
    "helm.sh/created": "{{.Release.Time.Seconds}}"
spec:
  replicas: {{.Replicas}}
  selector:
    name: {{.Release.Name}}-redis-sa
    mode: standalone
    provider: {{.Release.Name}}-redis-sa
  template:
    metadata:
      labels:
        name: {{.Release.Name}}-redis-sa
        mode: standalone
        provider: {{.Release.Name}}-redis-sa
        app: redis-standalone
    spec:
      containers:
      - name: redis-standalone
        image: kubernetes/redis:v1
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
