apiVersion: v1
kind: ReplicationController
metadata:
  name: es-logging-master
  labels:
    component: es-logging
    role: master
spec:
  replicas: 1
  selector:
    component: es-logging
    role: master
  template:
    metadata:
      labels:
        component: es-logging
        role: master
    spec:
      serviceAccount: es-logging
      containers:
      - name: es-logging-master
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/cafebazaar/elasticsearch-cluster-kubernetes
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: DISCOVERY_SERVICE
          value: es-logging-discovery
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
