name: monitoring
from:
  name: monitoring
  version: 0.0.1
  repo: https://github.com/cafebazaar/charts.git
home: http://github.com/kubernetes/helm
version: 0.0.1
description: Monitoring for Kubernetes
