apiVersion: extensions/v1beta1
kind: DaemonSet 
metadata:
  labels:
    name: influxGrafana
  name: influxdb-grafana
spec:
  selector:
    matchLabels:
      name: influxGrafana
  template:
    metadata:
      labels:
        name: influxGrafana
    spec:
      containers:
      - name: influxdb
        image: kubernetes/heapster_influxdb:v0.5
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      - name: grafana
        image: gcr.io/google_containers/heapster_grafana:v2.6.0-2
        env:
          - name: INFLUXDB_SERVICE_URL
            value: http://monitoring-influxdb:8086
          - name: GF_SERVER_ROOT_URL
            value: /api/v1/proxy/namespaces/{{ .Release.Namespace }}/services/monitoring-grafana/
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "false"
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: grafana-storage
        emptyDir: {}
      nodeSelector:
        monitoring: "true"
