apiVersion: v2
kind: Service
metadata:
    name: {{.Release.Name}}-talkative
    labels:
      heritage: helm
      chartName: {{.Chart.Name}}
      chartVersion: {{.Chart.Version | quote}}
      provider: {{.Release.Name}}-talkative
    annotations:
      "helm.sh/created": "{{.Release.Time.Seconds}}"
spec:
  ports:
  - port: {{.Port}}
  selector:
    provider: {{.Release.Name}}-talkative

