apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-canary
  labels:
    heritage: helm
    chartName: {{.Chart.Name | quote}}
    chartVersion: {{.Chart.Version | quote}}
    provider: {{.Release.Name}}-canary
  annotations:
    "helm.sh/created": "{{.Release.Time.Seconds}}"
spec:
  ports:
  - port: 80
  selector:
    provider: {{.Release.Name}}-canary
