apiVersion: v1
kind: ReplicationController 
metadata:
  name: {{.Release.Name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{.Release.Name}}
        provider: {{.Release.Name}}
        app: canary-release
    spec:
      containers:
      - name: {{.Release.Name}}
        image: quay.io/cafebazaar/canary:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_ONE
          value: "{{.Values.ServiceOne}}"
        - name: SERVICE_TWO
          value: "{{.Values.ServiceTwo}}"
        - name: SERVICE_ONE_WEIGHT
          value: "{{.Values.ServiceOneWeight}}"
        - name: SERVICE_TWO_WEIGHT
          value: "{{.Values.ServiceTwoWeight}}"
      imagePullSecrets:
        - name: registrykey 
